{{- if .Values.controllerplugin.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dummy-autofuse-csi.serviceAccountName.controllerplugin" . }}
  labels:
    {{- include "dummy-autofuse-csi.labels" . | nindent 4 }}
    component: controllerplugin
{{- end }}

