{{- if .Values.storageClass.create }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.className }}
  labels:
    {{- include "dummy-autofuse-csi.labels" . | nindent 4 }}
provisioner: {{ .Values.csiDriverName }}
{{- end }}
