apiVersion: v1
kind: PersistentVolume
metadata:
  name: dummy-autofuse-pv
spec:
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 1
  csi:
    driver: dummy-autofuse-csi
    volumeHandle: dummy-autofuse-csi-default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dummy-autofuse-pvc
  namespace: default
spec:
  accessModes:
   - ReadOnlyMany
  resources:
    requests:
      storage: 1
  volumeName: dummy-autofuse-pv
  storageClassName: ""
