apiVersion: v1
kind: Pod
metadata:
  name: dummy-fuse-pod
spec:
  containers:
  - name: dummy-workload
    image: registry.cern.ch/rvasek/dummy-autofuse-csi:master
    imagePullPolicy: Always
    command: ["/usr/local/bin/dummy-fuse-workload"]
    args: [
      "--file", "/mnt/xx/dummy-file.txt",
      # "--exit-on-error",
      # "--keep-open",
    ]
    volumeMounts:
    - name: mypvc
      mountPath: /mnt
      mountPropagation: HostToContainer
  volumes:
  - name: mypvc
    persistentVolumeClaim: 
      claimName: dummy-autofuse-pvc
      readOnly: false
